{% set name = "curies" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/curies-{{ version }}.tar.gz
  sha256: d208ad40b5e40b532285c917f116001f9e887a48dda54e6eedd10e514ea6aa1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - pytrie
    - pydantic
    - requests

test:
  imports:
    - curies
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cthoyt/curies
  summary: Idiomatic conversion between URIs and compact URIs (CURIEs).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
